import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css';
import Link from 'next/link';
import dynamic from 'next/dynamic';

const RA = dynamic(() => import('../components/admin-dashboard/AdminDashboard.js'), {
  ssr: false,
});



export default function Home() {

  // const [incommingMessages, setIncommingMessages] = useState([]);
  // const addMessage = (message) => {
  //   setIncommingMessages((incommingMessages) => [...incommingMessages, message]);

  //   console.log('incommingMessages: ');
  //   console.log(incommingMessages);
  // }
  // const clearMessages = () => {
  //   setIncommingMessages(() => []);
  // }

  // const incommingMessageHandlers = useRef([
  //   {
  //     topic: 'SERVER/#',
  //     handler: (msg) => {
  //       addMessage(msg);
  //     },
  //   },
  // ]);

  // const mqttClientRef = useRef(null);
  // const setMqttClient = (client) => {
  //   mqttClientRef.current = client
  // };

  // useMqtt({
  //   uri: process.env.NEXT_PUBLIC_MQTT_URI,
  //   options: {
  //     username: process.env.NEXT_PUBLIC_MQTT_USERNAME,
  //     password: process.env.NEXT_PUBLIC_MQTT_PASSWORD,
  //     clientId: process.env.NEXT_PUBLIC_MQTT_CLIENTID,
  //   },
  //   topicHandlers: incommingMessageHandlers.current,
  //   onConnectedHandler: (client) => setMqttClient(client),
  // });



  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="SamaControl PWA" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0" />
        <link rel="manifest" href="../public/manifest.json" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <RA />
    </div>
  );

  // return (
  //   <div className={styles.container}>
  //     <Head>
  //       <title>Create Next App</title>
  //       <meta name="description" content="Generated by create next app" />
  //       <link rel="icon" href="/favicon.ico" />
  //     </Head>

  //     <main className={styles.main}>
  //       <h1 className={styles.title}>
  //         Welcome to <a href="https://nextjs.org">Next.js!</a>

  //         <p>happy learning...</p>
  //         See {' '}
  //         <Link href='/dashboard/react-admin-dashboard'>
  //           <a>this page</a>
  //         </Link>

  //       </h1>

  //       <p className={styles.description}>
  //         Get started by editing{' '}
  //         <code className={styles.code}>pages/index.js</code>
  //       </p>

  //       <div className={styles.grid}>
  //         <a href="https://nextjs.org/docs" className={styles.card}>
  //           <h2>Documentation &rarr;</h2>
  //           <p>Find in-depth information about Next.js features and API.</p>
  //         </a>

  //         <a href="https://nextjs.org/learn" className={styles.card}>
  //           <h2>Learn &rarr;</h2>
  //           <p>Learn about Next.js in an interactive course with quizzes!</p>
  //         </a>

  //         <a
  //           href="https://github.com/vercel/next.js/tree/master/examples"
  //           className={styles.card}
  //         >
  //           <h2>Examples &rarr;</h2>
  //           <p>Discover and deploy boilerplate example Next.js projects.</p>
  //         </a>

  //         <a
  //           href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //           className={styles.card}
  //         >
  //           <h2>Deploy &rarr;</h2>
  //           <p>
  //             Instantly deploy your Next.js site to a public URL with Vercel.
  //           </p>
  //         </a>
  //       </div>
  //     </main>

  //     <footer className={styles.footer}>
  //       <a
  //         href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
  //         target="_blank"
  //         rel="noopener noreferrer"
  //       >
  //         Powered by{' '}
  //         <span className={styles.logo}>
  //           <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
  //         </span>
  //       </a>
  //     </footer>
  //   </div>
  // );
}
